### ISSUE TITLE
Cannot do npm install on the blog

### ISSUE THREAD

**Issue by ctanakul** [tupleblog/tupleblog.github.io#14]
Hello guys,

I'm trying to run the blog locally. However, when I run `npm install`, I got the following error:

```
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chainatee/tupleblog.github.io/npm-debug.log
npm ERR! code 1
```

I'm using Ubuntu 14.04. Let me know if you need more information for clarification.

**Comment by bluenex** [comment]
I tried reproduced on Ubuntu 14.04 but didn't get the same results. I think this is a problem of the latest version of npm with the package `gifsicle`. My npm version is `2.5.1` on node version `0.12.0` which is pretty old. The workaround could be taking `grunt-contrib-imagemin`, which depents on `gifsicle`, out of `packages.json` but that is not recommended because we may lack of image manipulation capability. 

I still have no plan on upgrading node and npm on my Ubuntu machine soon. However, I will check on MacOS how I managed to run with npm 3.x+. 

Thank you for the report. :smile:

**Comment by bluenex** [comment]
I have faced this same problem on Windows and `gifsicle` error has been solved by changing `grunt-contrib-imagemin` to version `~0.8.0` (see 596ec8e9bd5712fd0069868ad0b4d4fb72a09ee4).

However to be able to run on Windows (at least now) it requires multiple steps to be done and I will note those in `README.md`.
